### ISSUE TITLE
node hacked.js won't run

### ISSUE THREAD

**Issue by yomete** [maxdeviant/hacked#12]
Hi, I pulled you repo and did NPM install.
Everything worked out fine, then I tried node hacked.js and i got this error message:

module.js:328
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/user/Documents/batcave/hacked-master/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by maxdeviant** [comment]
What version of Node are you running?

Mongoose is compiled natively, and it could be that the version of Mongoose in the `package.json` needs to be updated to a later version.

**Comment by yomete** [comment]
I changed my version of the mongoose and everything works now.
